version: 0.2

phases:
  install:
    commands:
      - apt install curl
      - curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
      - export NVM_DIR="$HOME/.nvm"
      - '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'
      - '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"'
      - . "$NVM_DIR/nvm.sh" && nvm install 12.20.0 && echo "node installed Devops Team"
      - npm install -g @angular/cli@9.0.7 --unsafe-perm=true --allow-root
  pre_build:
    commands:
      - npm i
  build:
    commands:
      - npm run build
      - pwd
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist