import { LanguageList } from "./languagelist.model";

export class StudentUpdateRequest {
    student_id: string | null;
    profile_image :string | null;
    parent_id: string | null;
    school_id: string | null;
    name: string | null;
    gender: string | null;
    class: string | null;
    section: string | null;
    branch_id: string | null;
    subject: any | null;
    address: string | null;
    country: string | null;
    state: string | null;
    city: string | null;
    pincode: string | null;
    aadhar: string | null;
    sts_no: string | null;
    rte_student: string | null;
    religion: string | null;
    caste: string | null;
    mother_tongue: string | null;
    blood_gr: string | null;
    mode_of_transp: string | null;
    medical_cond: string | null;
    wear_glasses: string | null;
    email: string | null;
    admission_no: string | null;
    dob: string | null;
    guardian: string | null;
    primaryParent: string | null;
    father_name: string | null;
    f_contact_number: string | null;
    f_email: string | null;
    f_qualification: string | null;
    f_occupation:string | null;
    f_aadhar_no: string | null;
    mobile_to_reg_student: string | null;
    language_proficiency: LanguageList[] | null;
    mother_name: string | null;
    m_contact_number: string | null;
    m_email: string | null;
    m_qualification: string | null;
    m_occupation: string | null;
    m_aadhar_no: string | null;
    m_mobile_to_reg_student: string | null;
    m_language_proficiency: LanguageList[] | null;
    guardian_name: string | null;
    guardian_mobile: string | null;
    g_email: string | null;
    g_qualificaton: string | null;
    g_occupation: string | null;
    g_aadhar: string | null;
    guardian_mobile_to_reg_student: string | null;
    g_language_proficiency: LanguageList[] | null;
  documents: { birthCertificate: any; incomeCertificate: any; aadhar: any; fatherAadhaarDoc: any; motherAadhaarDoc: any; };
  docAttachments: { birthCertificate: any; incomeCertificate: any; aadhar: any; fatherAadhaarDoc: any; motherAadhaarDoc: any; };
}